### ISSUE TITLE
No Provider for StateService.

### ISSUE THREAD

**Issue by muscleman** [ui-router/sample-app-angular#5]
Hi,

1) cloned sample-app-ng2
2) ng-serve complained about not finding message or folder types so I extracted them both into separate files
3) changed any references to include import { Folder } from './folder.interface';
import { Message} from './message.interface';
4) app.module.ts. had to do a cast in the imports section. config: <any>routerConfigFn
5) app compiles and serves with ng serve but fails with ng serve --aot
6) transitions not working, following is displayed in developer tools

Transition Rejection($id: 0 type: 6, message: The transition errored, detail: Error: No provider for StateService!)
Error
at injectionError (http://localhost:4200/vendor.bundle.js:2909:5) [angular]
at noProviderError (http://localhost:4200/vendor.bundle.js:2947:5) [angular]
at ReflectiveInjector_.prototype._throwOrNull (http://localhost:4200/vendor.bundle.js:4448:13) [angular]
at ReflectiveInjector_.prototype._getByKeyDefault (http://localhost:4200/vendor.bundle.js:4487:13) [angular]
at ReflectiveInjector_.prototype._getByKey (http://localhost:4200/vendor.bundle.js:4419:13) [angular]
at ReflectiveInjector_.prototype.get (http://localhost:4200/vendor.bundle.js:4288:9) [angular]
at NgModuleInjector.prototype.get (http://localhost:4200/vendor.bundle.js:5256:9) [angular]
at resolveDep (http://localhost:4200/vendor.bundle.js:12717:5) [angular]
at createClass (http://localhost:4200/vendor.bundle.js:12581:17) [angular]
at createDirectiveInstance (http://localhost:4200/vendor.bundle.js:12401:5) [angular]
at createViewNodes (http://localhost:4200/vendor.bundle.js:13764:17) [angular]
at createRoot

This was working 11 days ago.

Thanks
Gary

**Comment by muscleman** [comment]
I deleted the node_modules folder from the latest clone and replaced with one from 11 days ago.
it compiled and worked.
then i removed the @uirouter folder and did npm install 
and it also worked.
currently getting a migratewarn.js about @uirouter/rs@0.3.1 requires a peer of @uirouter/core@5.00 but none was installed.

**Comment by christopherthielen** [comment]
I suspect this is related to #4 
Try again today and please report back.

**Comment by muscleman** [comment]
Hi,
 
With sample-app-angular

1) I removed `@uirouter/core` from package.json.  
2) removed the node_modules direct. 
3) npm install
4) ng serve --aot --sm.

Seems to have fix this

did the same with my project and blew up.
Guess it's fixed.
Thanks

**Comment by muscleman** [comment]
looks good now, i had so other dependencies i needed to remove.
